<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE tracings [
  <!ELEMENT tracings       (samplespacing,imagesize,path*,fill*)>
  <!ELEMENT imagesize      EMPTY>
  <!ELEMENT samplespacing  EMPTY>
  <!ELEMENT path           (point+)>
  <!ELEMENT point          EMPTY>
  <!ELEMENT fill           (node*)>
  <!ELEMENT node           EMPTY>
  <!ATTLIST samplespacing  x                 CDATA           #REQUIRED>
  <!ATTLIST samplespacing  y                 CDATA           #REQUIRED>
  <!ATTLIST samplespacing  z                 CDATA           #REQUIRED>
  <!ATTLIST samplespacing  units             CDATA           #REQUIRED>
  <!ATTLIST imagesize      width             CDATA           #REQUIRED>
  <!ATTLIST imagesize      height            CDATA           #REQUIRED>
  <!ATTLIST imagesize      depth             CDATA           #REQUIRED>
  <!ATTLIST path           id                CDATA           #REQUIRED>
  <!ATTLIST path           primary           CDATA           #IMPLIED>
  <!ATTLIST path           name              CDATA           #IMPLIED>
  <!ATTLIST path           startson          CDATA           #IMPLIED>
  <!ATTLIST path           startsindex       CDATA           #IMPLIED>
  <!ATTLIST path           startsx           CDATA           #IMPLIED>
  <!ATTLIST path           startsy           CDATA           #IMPLIED>
  <!ATTLIST path           startsz           CDATA           #IMPLIED>
  <!ATTLIST path           endson            CDATA           #IMPLIED>
  <!ATTLIST path           endsindex         CDATA           #IMPLIED>
  <!ATTLIST path           endsx             CDATA           #IMPLIED>
  <!ATTLIST path           endsy             CDATA           #IMPLIED>
  <!ATTLIST path           endsz             CDATA           #IMPLIED>
  <!ATTLIST path           reallength        CDATA           #IMPLIED>
  <!ATTLIST path           usefitted         (true|false)    #IMPLIED>
  <!ATTLIST path           fitted            CDATA           #IMPLIED>
  <!ATTLIST path           fittedversionof   CDATA           #IMPLIED>
  <!ATTLIST path           swctype           CDATA           #IMPLIED>
  <!ATTLIST path           color             CDATA           #IMPLIED>
  <!ATTLIST point          x                 CDATA           #REQUIRED>
  <!ATTLIST point          y                 CDATA           #REQUIRED>
  <!ATTLIST point          z                 CDATA           #REQUIRED>
  <!ATTLIST point          xd                CDATA           #IMPLIED>
  <!ATTLIST point          yd                CDATA           #IMPLIED>
  <!ATTLIST point          zd                CDATA           #IMPLIED>
  <!ATTLIST point          tx                CDATA           #IMPLIED>
  <!ATTLIST point          ty                CDATA           #IMPLIED>
  <!ATTLIST point          tz                CDATA           #IMPLIED>
  <!ATTLIST point          r                 CDATA           #IMPLIED>
  <!ATTLIST fill           id                CDATA           #REQUIRED>
  <!ATTLIST fill           frompaths         CDATA           #IMPLIED>
  <!ATTLIST fill           metric            CDATA           #REQUIRED>
  <!ATTLIST fill           threshold         CDATA           #REQUIRED>
  <!ATTLIST fill           volume            CDATA           #IMPLIED>
  <!ATTLIST node           id                CDATA           #REQUIRED>
  <!ATTLIST node           x                 CDATA           #REQUIRED>
  <!ATTLIST node           y                 CDATA           #REQUIRED>
  <!ATTLIST node           z                 CDATA           #REQUIRED>
  <!ATTLIST node           previousid        CDATA           #IMPLIED>
  <!ATTLIST node           distance          CDATA           #REQUIRED>
  <!ATTLIST node           status            (open|closed)   #REQUIRED>
]>

<tracings>
  <samplespacing x="0.3021955490112304" y="0.3021955490112304" z="1.0" units="microns"/>
  <imagesize width="1024" height="1024" depth="80"/>
  <path id="1" swctype="1" color="none" usefitted="true" fitted="41" name="Path (1)" reallength="23.104615789781143">
    <point x="836" y="392" z="38" xd="252.63547897338867" yd="118.46065521240234" zd="38.0"/>
    <point x="836" y="393" z="38" xd="252.63547897338867" yd="118.76285076141357" zd="38.0"/>
    <point x="836" y="394" z="38" xd="252.63547897338867" yd="119.0650463104248" zd="38.0"/>
    <point x="836" y="395" z="38" xd="252.63547897338867" yd="119.36724185943604" zd="38.0"/>
    <point x="836" y="396" z="38" xd="252.63547897338867" yd="119.66943740844727" zd="38.0"/>
    <point x="836" y="397" z="38" xd="252.63547897338867" yd="119.9716329574585" zd="38.0"/>
    <point x="836" y="398" z="38" xd="252.63547897338867" yd="120.27382850646973" zd="38.0"/>
    <point x="836" y="399" z="38" xd="252.63547897338867" yd="120.57602405548096" zd="38.0"/>
    <point x="836" y="400" z="38" xd="252.63547897338867" yd="120.87821960449219" zd="38.0"/>
    <point x="836" y="401" z="38" xd="252.63547897338867" yd="121.18041515350342" zd="38.0"/>
    <point x="836" y="402" z="38" xd="252.63547897338867" yd="121.48261070251465" zd="38.0"/>
    <point x="836" y="403" z="38" xd="252.63547897338867" yd="121.78480625152588" zd="38.0"/>
    <point x="836" y="404" z="38" xd="252.63547897338867" yd="122.08700180053711" zd="38.0"/>
    <point x="836" y="405" z="38" xd="252.63547897338867" yd="122.38919734954834" zd="38.0"/>
    <point x="836" y="406" z="38" xd="252.63547897338867" yd="122.69139289855957" zd="38.0"/>
    <point x="836" y="407" z="38" xd="252.63547897338867" yd="122.9935884475708" zd="38.0"/>
    <point x="836" y="408" z="38" xd="252.63547897338867" yd="123.29578399658203" zd="38.0"/>
    <point x="836" y="409" z="38" xd="252.63547897338867" yd="123.59797954559326" zd="38.0"/>
    <point x="836" y="410" z="38" xd="252.63547897338867" yd="123.90017509460449" zd="38.0"/>
    <point x="836" y="411" z="38" xd="252.63547897338867" yd="124.20237064361572" zd="38.0"/>
    <point x="836" y="412" z="38" xd="252.63547897338867" yd="124.50456619262695" zd="38.0"/>
    <point x="836" y="413" z="38" xd="252.63547897338867" yd="124.80676174163818" zd="38.0"/>
    <point x="836" y="414" z="38" xd="252.63547897338867" yd="125.10895729064941" zd="38.0"/>
    <point x="836" y="415" z="38" xd="252.63547897338867" yd="125.41115283966064" zd="38.0"/>
    <point x="837" y="416" z="38" xd="252.9376745223999" yd="125.71334838867188" zd="38.0"/>
    <point x="838" y="417" z="38" xd="253.23987007141113" yd="126.0155439376831" zd="38.0"/>
    <point x="839" y="418" z="38" xd="253.54206562042236" yd="126.31773948669434" zd="38.0"/>
    <point x="840" y="419" z="38" xd="253.8442611694336" yd="126.61993503570557" zd="38.0"/>
    <point x="841" y="420" z="38" xd="254.14645671844482" yd="126.9221305847168" zd="38.0"/>
    <point x="842" y="421" z="38" xd="254.44865226745605" yd="127.22432613372803" zd="38.0"/>
    <point x="843" y="422" z="38" xd="254.75084781646729" yd="127.52652168273926" zd="38.0"/>
    <point x="844" y="423" z="38" xd="255.05304336547852" yd="127.82871723175049" zd="38.0"/>
    <point x="845" y="424" z="38" xd="255.35523891448975" yd="128.13091278076172" zd="38.0"/>
    <point x="846" y="425" z="38" xd="255.65743446350098" yd="128.43310832977295" zd="38.0"/>
    <point x="847" y="426" z="38" xd="255.9596300125122" yd="128.73530387878418" zd="38.0"/>
    <point x="848" y="427" z="38" xd="256.26182556152344" yd="129.0374994277954" zd="38.0"/>
    <point x="849" y="428" z="38" xd="256.56402111053467" yd="129.33969497680664" zd="38.0"/>
    <point x="850" y="429" z="38" xd="256.8662166595459" yd="129.64189052581787" zd="38.0"/>
    <point x="851" y="430" z="38" xd="257.16841220855713" yd="129.9440860748291" zd="38.0"/>
    <point x="852" y="431" z="38" xd="257.47060775756836" yd="130.24628162384033" zd="38.0"/>
    <point x="853" y="432" z="38" xd="257.7728033065796" yd="130.54847717285156" zd="38.0"/>
    <point x="854" y="433" z="38" xd="258.0749988555908" yd="130.8506727218628" zd="38.0"/>
    <point x="854" y="434" z="38" xd="258.0749988555908" yd="131.15286827087402" zd="38.0"/>
    <point x="854" y="435" z="38" xd="258.0749988555908" yd="131.45506381988525" zd="38.0"/>
    <point x="854" y="436" z="38" xd="258.0749988555908" yd="131.75725936889648" zd="38.0"/>
    <point x="854" y="437" z="38" xd="258.0749988555908" yd="132.05945491790771" zd="38.0"/>
    <point x="854" y="438" z="38" xd="258.0749988555908" yd="132.36165046691895" zd="38.0"/>
    <point x="854" y="439" z="38" xd="258.0749988555908" yd="132.66384601593018" zd="38.0"/>
    <point x="854" y="440" z="38" xd="258.0749988555908" yd="132.9660415649414" zd="38.0"/>
    <point x="854" y="441" z="38" xd="258.0749988555908" yd="133.26823711395264" zd="38.0"/>
    <point x="854" y="442" z="38" xd="258.0749988555908" yd="133.57043266296387" zd="38.0"/>
    <point x="854" y="443" z="38" xd="258.0749988555908" yd="133.8726282119751" zd="38.0"/>
    <point x="854" y="444" z="38" xd="258.0749988555908" yd="134.17482376098633" zd="38.0"/>
    <point x="854" y="445" z="38" xd="258.0749988555908" yd="134.47701930999756" zd="38.0"/>
    <point x="854" y="446" z="38" xd="258.0749988555908" yd="134.7792148590088" zd="38.0"/>
    <point x="854" y="447" z="38" xd="258.0749988555908" yd="135.08141040802002" zd="38.0"/>
    <point x="854" y="448" z="38" xd="258.0749988555908" yd="135.38360595703125" zd="38.0"/>
    <point x="854" y="449" z="38" xd="258.0749988555908" yd="135.68580150604248" zd="38.0"/>
    <point x="854" y="450" z="38" xd="258.0749988555908" yd="135.9879970550537" zd="38.0"/>
    <point x="854" y="451" z="38" xd="258.0749988555908" yd="136.29019260406494" zd="38.0"/>
    <point x="854" y="452" z="38" xd="258.0749988555908" yd="136.59238815307617" zd="38.0"/>
    <point x="854" y="453" z="38" xd="258.0749988555908" yd="136.8945837020874" zd="38.0"/>
    <point x="854" y="454" z="38" xd="258.0749988555908" yd="137.19677925109863" zd="38.0"/>
    <point x="854" y="455" z="38" xd="258.0749988555908" yd="137.49897480010986" zd="38.0"/>
    <point x="854" y="456" z="38" xd="258.0749988555908" yd="137.8011703491211" zd="38.0"/>
    <point x="854" y="457" z="38" xd="258.0749988555908" yd="138.10336589813232" zd="38.0"/>
    <point x="854" y="458" z="38" xd="258.0749988555908" yd="138.40556144714355" zd="38.0"/>
    <point x="854" y="459" z="38" xd="258.0749988555908" yd="138.70775699615479" zd="38.0"/>
    <point x="854" y="460" z="38" xd="258.0749988555908" yd="139.00995254516602" zd="38.0"/>
    <point x="854" y="461" z="38" xd="258.0749988555908" yd="139.31214809417725" zd="38.0"/>
  </path>
  <path id="2" swctype="7" color="none" usefitted="false" name="somaD" reallength="13.956528577402418">
    <point x="829" y="436" z="38" xd="250.52011013031006" yd="131.75725936889648" zd="38.0"/>
    <point x="830" y="435" z="38" xd="250.8223056793213" yd="131.45506381988525" zd="38.0"/>
    <point x="831" y="434" z="38" xd="251.12450122833252" yd="131.15286827087402" zd="38.0"/>
    <point x="832" y="433" z="38" xd="251.42669677734375" yd="130.8506727218628" zd="38.0"/>
    <point x="833" y="432" z="38" xd="251.72889232635498" yd="130.54847717285156" zd="38.0"/>
    <point x="834" y="431" z="38" xd="252.0310878753662" yd="130.24628162384033" zd="38.0"/>
    <point x="835" y="430" z="38" xd="252.33328342437744" yd="129.9440860748291" zd="38.0"/>
    <point x="836" y="429" z="38" xd="252.63547897338867" yd="129.64189052581787" zd="38.0"/>
    <point x="837" y="428" z="38" xd="252.9376745223999" yd="129.33969497680664" zd="38.0"/>
    <point x="838" y="427" z="38" xd="253.23987007141113" yd="129.0374994277954" zd="38.0"/>
    <point x="839" y="426" z="38" xd="253.54206562042236" yd="128.73530387878418" zd="38.0"/>
    <point x="840" y="425" z="38" xd="253.8442611694336" yd="128.43310832977295" zd="38.0"/>
    <point x="841" y="424" z="38" xd="254.14645671844482" yd="128.13091278076172" zd="38.0"/>
    <point x="842" y="423" z="38" xd="254.44865226745605" yd="127.82871723175049" zd="38.0"/>
    <point x="843" y="423" z="38" xd="254.75084781646729" yd="127.82871723175049" zd="38.0"/>
    <point x="844" y="423" z="38" xd="255.05304336547852" yd="127.82871723175049" zd="38.0"/>
    <point x="845" y="423" z="38" xd="255.35523891448975" yd="127.82871723175049" zd="38.0"/>
    <point x="846" y="423" z="38" xd="255.65743446350098" yd="127.82871723175049" zd="38.0"/>
    <point x="847" y="424" z="38" xd="255.9596300125122" yd="128.13091278076172" zd="38.0"/>
    <point x="848" y="424" z="38" xd="256.26182556152344" yd="128.13091278076172" zd="38.0"/>
    <point x="849" y="424" z="38" xd="256.56402111053467" yd="128.13091278076172" zd="38.0"/>
    <point x="850" y="424" z="38" xd="256.8662166595459" yd="128.13091278076172" zd="38.0"/>
    <point x="851" y="424" z="38" xd="257.16841220855713" yd="128.13091278076172" zd="38.0"/>
    <point x="852" y="423" z="38" xd="257.47060775756836" yd="127.82871723175049" zd="38.0"/>
    <point x="853" y="422" z="38" xd="257.7728033065796" yd="127.52652168273926" zd="38.0"/>
    <point x="854" y="421" z="38" xd="258.0749988555908" yd="127.22432613372803" zd="38.0"/>
    <point x="855" y="420" z="38" xd="258.37719440460205" yd="126.9221305847168" zd="38.0"/>
    <point x="856" y="419" z="38" xd="258.6793899536133" yd="126.61993503570557" zd="38.0"/>
    <point x="857" y="418" z="38" xd="258.9815855026245" yd="126.31773948669434" zd="38.0"/>
    <point x="858" y="417" z="38" xd="259.28378105163574" yd="126.0155439376831" zd="38.0"/>
    <point x="859" y="416" z="38" xd="259.585976600647" yd="125.71334838867188" zd="38.0"/>
    <point x="860" y="415" z="38" xd="259.8881721496582" yd="125.41115283966064" zd="38.0"/>
    <point x="861" y="414" z="38" xd="260.19036769866943" yd="125.10895729064941" zd="38.0"/>
    <point x="862" y="413" z="38" xd="260.49256324768066" yd="124.80676174163818" zd="38.0"/>
    <point x="863" y="412" z="38" xd="260.7947587966919" yd="124.50456619262695" zd="38.0"/>
    <point x="864" y="411" z="38" xd="261.0969543457031" yd="124.20237064361572" zd="38.0"/>
  </path>
  <path id="3" swctype="2" color="none" usefitted="true" fitted="42" startson="1" startx="252.63547897338867" starty="118.46065521240234" startz="38.0" startsindex="0" name="Path (3)" reallength="132.55488072997707">
    <point x="836" y="392" z="38" xd="252.63547897338867" yd="118.46065521240234" zd="38.0"/>
    <point x="836" y="391" z="38" xd="252.63547897338867" yd="118.15845966339111" zd="38.0"/>
    <point x="836" y="390" z="38" xd="252.63547897338867" yd="117.85626411437988" zd="38.0"/>
    <point x="836" y="389" z="38" xd="252.63547897338867" yd="117.55406856536865" zd="38.0"/>
    <point x="835" y="388" z="38" xd="252.33328342437744" yd="117.25187301635742" zd="38.0"/>
    <point x="835" y="387" z="38" xd="252.33328342437744" yd="116.94967746734619" zd="38.0"/>
    <point x="835" y="386" z="38" xd="252.33328342437744" yd="116.64748191833496" zd="38.0"/>
    <point x="834" y="385" z="38" xd="252.0310878753662" yd="116.34528636932373" zd="38.0"/>
    <point x="833" y="384" z="38" xd="251.72889232635498" yd="116.0430908203125" zd="38.0"/>
    <point x="832" y="383" z="39" xd="251.42669677734375" yd="115.74089527130127" zd="39.0"/>
    <point x="832" y="382" z="39" xd="251.42669677734375" yd="115.43869972229004" zd="39.0"/>
    <point x="831" y="381" z="40" xd="251.12450122833252" yd="115.13650417327881" zd="40.0"/>
    <point x="831" y="380" z="40" xd="251.12450122833252" yd="114.83430862426758" zd="40.0"/>
    <point x="830" y="379" z="40" xd="250.8223056793213" yd="114.53211307525635" zd="40.0"/>
    <point x="829" y="378" z="40" xd="250.52011013031006" yd="114.22991752624512" zd="40.0"/>
    <point x="829" y="377" z="40" xd="250.52011013031006" yd="113.92772197723389" zd="40.0"/>
    <point x="829" y="376" z="40" xd="250.52011013031006" yd="113.62552642822266" zd="40.0"/>
    <point x="829" y="376" z="41" xd="250.52011013031006" yd="113.62552642822266" zd="41.0"/>
    <point x="829" y="375" z="42" xd="250.52011013031006" yd="113.32333087921143" zd="42.0"/>
    <point x="829" y="374" z="42" xd="250.52011013031006" yd="113.0211353302002" zd="42.0"/>
    <point x="829" y="373" z="42" xd="250.52011013031006" yd="112.71893978118896" zd="42.0"/>
    <point x="830" y="372" z="43" xd="250.8223056793213" yd="112.41674423217773" zd="43.0"/>
    <point x="830" y="371" z="43" xd="250.8223056793213" yd="112.1145486831665" zd="43.0"/>
    <point x="831" y="370" z="44" xd="251.12450122833252" yd="111.81235313415527" zd="44.0"/>
    <point x="831" y="369" z="44" xd="251.12450122833252" yd="111.51015758514404" zd="44.0"/>
    <point x="831" y="368" z="44" xd="251.12450122833252" yd="111.20796203613281" zd="44.0"/>
    <point x="831" y="367" z="44" xd="251.12450122833252" yd="110.90576648712158" zd="44.0"/>
    <point x="831" y="366" z="44" xd="251.12450122833252" yd="110.60357093811035" zd="44.0"/>
    <point x="832" y="365" z="45" xd="251.42669677734375" yd="110.30137538909912" zd="45.0"/>
    <point x="832" y="364" z="46" xd="251.42669677734375" yd="109.99917984008789" zd="46.0"/>
    <point x="833" y="363" z="46" xd="251.72889232635498" yd="109.69698429107666" zd="46.0"/>
    <point x="833" y="362" z="46" xd="251.72889232635498" yd="109.39478874206543" zd="46.0"/>
    <point x="833" y="361" z="46" xd="251.72889232635498" yd="109.0925931930542" zd="46.0"/>
    <point x="833" y="360" z="46" xd="251.72889232635498" yd="108.79039764404297" zd="46.0"/>
    <point x="833" y="359" z="47" xd="251.72889232635498" yd="108.48820209503174" zd="47.0"/>
    <point x="833" y="358" z="47" xd="251.72889232635498" yd="108.18600654602051" zd="47.0"/>
    <point x="833" y="357" z="47" xd="251.72889232635498" yd="107.88381099700928" zd="47.0"/>
    <point x="833" y="356" z="47" xd="251.72889232635498" yd="107.58161544799805" zd="47.0"/>
    <point x="833" y="355" z="47" xd="251.72889232635498" yd="107.27941989898682" zd="47.0"/>
    <point x="833" y="354" z="47" xd="251.72889232635498" yd="106.97722434997559" zd="47.0"/>
    <point x="833" y="353" z="47" xd="251.72889232635498" yd="106.67502880096436" zd="47.0"/>
    <point x="833" y="352" z="47" xd="251.72889232635498" yd="106.37283325195312" zd="47.0"/>
    <point x="832" y="351" z="47" xd="251.42669677734375" yd="106.0706377029419" zd="47.0"/>
    <point x="832" y="350" z="47" xd="251.42669677734375" yd="105.76844215393066" zd="47.0"/>
    <point x="832" y="350" z="48" xd="251.42669677734375" yd="105.76844215393066" zd="48.0"/>
    <point x="832" y="349" z="49" xd="251.42669677734375" yd="105.46624660491943" zd="49.0"/>
    <point x="832" y="348" z="50" xd="251.42669677734375" yd="105.1640510559082" zd="50.0"/>
    <point x="832" y="347" z="50" xd="251.42669677734375" yd="104.86185550689697" zd="50.0"/>
    <point x="831" y="346" z="51" xd="251.12450122833252" yd="104.55965995788574" zd="51.0"/>
    <point x="831" y="345" z="51" xd="251.12450122833252" yd="104.25746440887451" zd="51.0"/>
    <point x="831" y="344" z="51" xd="251.12450122833252" yd="103.95526885986328" zd="51.0"/>
    <point x="831" y="343" z="51" xd="251.12450122833252" yd="103.65307331085205" zd="51.0"/>
    <point x="830" y="342" z="51" xd="250.8223056793213" yd="103.35087776184082" zd="51.0"/>
    <point x="830" y="341" z="51" xd="250.8223056793213" yd="103.04868221282959" zd="51.0"/>
    <point x="830" y="340" z="51" xd="250.8223056793213" yd="102.74648666381836" zd="51.0"/>
    <point x="829" y="339" z="51" xd="250.52011013031006" yd="102.44429111480713" zd="51.0"/>
    <point x="829" y="338" z="51" xd="250.52011013031006" yd="102.1420955657959" zd="51.0"/>
    <point x="829" y="337" z="51" xd="250.52011013031006" yd="101.83990001678467" zd="51.0"/>
    <point x="829" y="336" z="51" xd="250.52011013031006" yd="101.53770446777344" zd="51.0"/>
    <point x="829" y="335" z="51" xd="250.52011013031006" yd="101.2355089187622" zd="51.0"/>
    <point x="829" y="334" z="51" xd="250.52011013031006" yd="100.93331336975098" zd="51.0"/>
    <point x="829" y="333" z="51" xd="250.52011013031006" yd="100.63111782073975" zd="51.0"/>
    <point x="829" y="332" z="51" xd="250.52011013031006" yd="100.32892227172852" zd="51.0"/>
    <point x="829" y="331" z="51" xd="250.52011013031006" yd="100.02672672271729" zd="51.0"/>
    <point x="829" y="330" z="51" xd="250.52011013031006" yd="99.72453117370605" zd="51.0"/>
    <point x="829" y="329" z="51" xd="250.52011013031006" yd="99.42233562469482" zd="51.0"/>
    <point x="828" y="328" z="51" xd="250.21791458129883" yd="99.1201400756836" zd="51.0"/>
    <point x="827" y="327" z="51" xd="249.9157190322876" yd="98.81794452667236" zd="51.0"/>
    <point x="827" y="326" z="51" xd="249.9157190322876" yd="98.51574897766113" zd="51.0"/>
    <point x="827" y="325" z="51" xd="249.9157190322876" yd="98.2135534286499" zd="51.0"/>
    <point x="826" y="324" z="51" xd="249.61352348327637" yd="97.91135787963867" zd="51.0"/>
    <point x="825" y="323" z="51" xd="249.31132793426514" yd="97.60916233062744" zd="51.0"/>
    <point x="824" y="322" z="51" xd="249.0091323852539" yd="97.30696678161621" zd="51.0"/>
    <point x="823" y="321" z="51" xd="248.70693683624268" yd="97.00477123260498" zd="51.0"/>
    <point x="822" y="320" z="51" xd="248.40474128723145" yd="96.70257568359375" zd="51.0"/>
    <point x="821" y="320" z="51" xd="248.10254573822021" yd="96.70257568359375" zd="51.0"/>
    <point x="820" y="319" z="51" xd="247.80035018920898" yd="96.40038013458252" zd="51.0"/>
    <point x="819" y="318" z="51" xd="247.49815464019775" yd="96.09818458557129" zd="51.0"/>
    <point x="818" y="318" z="51" xd="247.19595909118652" yd="96.09818458557129" zd="51.0"/>
    <point x="817" y="317" z="51" xd="246.8937635421753" yd="95.79598903656006" zd="51.0"/>
    <point x="816" y="316" z="51" xd="246.59156799316406" yd="95.49379348754883" zd="51.0"/>
    <point x="815" y="315" z="50" xd="246.28937244415283" yd="95.1915979385376" zd="50.0"/>
    <point x="814" y="314" z="50" xd="245.9871768951416" yd="94.88940238952637" zd="50.0"/>
    <point x="813" y="313" z="50" xd="245.68498134613037" yd="94.58720684051514" zd="50.0"/>
    <point x="812" y="312" z="50" xd="245.38278579711914" yd="94.2850112915039" zd="50.0"/>
    <point x="811" y="311" z="50" xd="245.0805902481079" yd="93.98281574249268" zd="50.0"/>
    <point x="810" y="310" z="50" xd="244.77839469909668" yd="93.68062019348145" zd="50.0"/>
    <point x="809" y="311" z="49" xd="244.47619915008545" yd="93.98281574249268" zd="49.0"/>
    <point x="808" y="310" z="48" xd="244.17400360107422" yd="93.68062019348145" zd="48.0"/>
    <point x="807" y="310" z="47" xd="243.871808052063" yd="93.68062019348145" zd="47.0"/>
    <point x="806" y="309" z="47" xd="243.56961250305176" yd="93.37842464447021" zd="47.0"/>
    <point x="805" y="309" z="47" xd="243.26741695404053" yd="93.37842464447021" zd="47.0"/>
    <point x="804" y="309" z="47" xd="242.9652214050293" yd="93.37842464447021" zd="47.0"/>
    <point x="803" y="308" z="47" xd="242.66302585601807" yd="93.07622909545898" zd="47.0"/>
    <point x="802" y="308" z="47" xd="242.36083030700684" yd="93.07622909545898" zd="47.0"/>
    <point x="801" y="308" z="47" xd="242.0586347579956" yd="93.07622909545898" zd="47.0"/>
    <point x="800" y="308" z="47" xd="241.75643920898438" yd="93.07622909545898" zd="47.0"/>
    <point x="799" y="308" z="47" xd="241.45424365997314" yd="93.07622909545898" zd="47.0"/>
    <point x="798" y="308" z="47" xd="241.1520481109619" yd="93.07622909545898" zd="47.0"/>
    <point x="797" y="307" z="47" xd="240.84985256195068" yd="92.77403354644775" zd="47.0"/>
    <point x="796" y="307" z="47" xd="240.54765701293945" yd="92.77403354644775" zd="47.0"/>
    <point x="795" y="307" z="47" xd="240.24546146392822" yd="92.77403354644775" zd="47.0"/>
    <point x="794" y="307" z="47" xd="239.943265914917" yd="92.77403354644775" zd="47.0"/>
    <point x="793" y="307" z="47" xd="239.64107036590576" yd="92.77403354644775" zd="47.0"/>
    <point x="792" y="307" z="47" xd="239.33887481689453" yd="92.77403354644775" zd="47.0"/>
    <point x="791" y="306" z="47" xd="239.0366792678833" yd="92.47183799743652" zd="47.0"/>
    <point x="790" y="306" z="47" xd="238.73448371887207" yd="92.47183799743652" zd="47.0"/>
    <point x="789" y="306" z="47" xd="238.43228816986084" yd="92.47183799743652" zd="47.0"/>
    <point x="788" y="305" z="47" xd="238.1300926208496" yd="92.1696424484253" zd="47.0"/>
    <point x="787" y="305" z="47" xd="237.82789707183838" yd="92.1696424484253" zd="47.0"/>
    <point x="786" y="305" z="47" xd="237.52570152282715" yd="92.1696424484253" zd="47.0"/>
    <point x="785" y="305" z="47" xd="237.22350597381592" yd="92.1696424484253" zd="47.0"/>
    <point x="784" y="305" z="47" xd="236.9213104248047" yd="92.1696424484253" zd="47.0"/>
    <point x="783" y="305" z="47" xd="236.61911487579346" yd="92.1696424484253" zd="47.0"/>
    <point x="782" y="305" z="47" xd="236.31691932678223" yd="92.1696424484253" zd="47.0"/>
    <point x="781" y="305" z="47" xd="236.014723777771" yd="92.1696424484253" zd="47.0"/>
    <point x="780" y="306" z="47" xd="235.71252822875977" yd="92.47183799743652" zd="47.0"/>
    <point x="779" y="306" z="47" xd="235.41033267974854" yd="92.47183799743652" zd="47.0"/>
    <point x="778" y="307" z="47" xd="235.1081371307373" yd="92.77403354644775" zd="47.0"/>
    <point x="777" y="307" z="47" xd="234.80594158172607" yd="92.77403354644775" zd="47.0"/>
    <point x="776" y="307" z="47" xd="234.50374603271484" yd="92.77403354644775" zd="47.0"/>
    <point x="775" y="307" z="47" xd="234.2015504837036" yd="92.77403354644775" zd="47.0"/>
    <point x="774" y="307" z="47" xd="233.89935493469238" yd="92.77403354644775" zd="47.0"/>
    <point x="773" y="307" z="47" xd="233.59715938568115" yd="92.77403354644775" zd="47.0"/>
    <point x="772" y="307" z="47" xd="233.29496383666992" yd="92.77403354644775" zd="47.0"/>
    <point x="771" y="307" z="47" xd="232.9927682876587" yd="92.77403354644775" zd="47.0"/>
    <point x="770" y="307" z="47" xd="232.69057273864746" yd="92.77403354644775" zd="47.0"/>
    <point x="769" y="307" z="47" xd="232.38837718963623" yd="92.77403354644775" zd="47.0"/>
    <point x="768" y="307" z="47" xd="232.086181640625" yd="92.77403354644775" zd="47.0"/>
    <point x="767" y="307" z="47" xd="231.78398609161377" yd="92.77403354644775" zd="47.0"/>
    <point x="766" y="307" z="47" xd="231.48179054260254" yd="92.77403354644775" zd="47.0"/>
    <point x="765" y="307" z="47" xd="231.1795949935913" yd="92.77403354644775" zd="47.0"/>
    <point x="764" y="307" z="47" xd="230.87739944458008" yd="92.77403354644775" zd="47.0"/>
    <point x="763" y="306" z="47" xd="230.57520389556885" yd="92.47183799743652" zd="47.0"/>
    <point x="762" y="306" z="47" xd="230.27300834655762" yd="92.47183799743652" zd="47.0"/>
    <point x="761" y="306" z="47" xd="229.9708127975464" yd="92.47183799743652" zd="47.0"/>
    <point x="760" y="305" z="47" xd="229.66861724853516" yd="92.1696424484253" zd="47.0"/>
    <point x="759" y="304" z="47" xd="229.36642169952393" yd="91.86744689941406" zd="47.0"/>
    <point x="758" y="304" z="47" xd="229.0642261505127" yd="91.86744689941406" zd="47.0"/>
    <point x="757" y="303" z="47" xd="228.76203060150146" yd="91.56525135040283" zd="47.0"/>
    <point x="756" y="302" z="47" xd="228.45983505249023" yd="91.2630558013916" zd="47.0"/>
    <point x="755" y="302" z="47" xd="228.157639503479" yd="91.2630558013916" zd="47.0"/>
    <point x="754" y="301" z="47" xd="227.85544395446777" yd="90.96086025238037" zd="47.0"/>
    <point x="753" y="300" z="46" xd="227.55324840545654" yd="90.65866470336914" zd="46.0"/>
    <point x="752" y="300" z="46" xd="227.2510528564453" yd="90.65866470336914" zd="46.0"/>
    <point x="751" y="300" z="46" xd="226.94885730743408" yd="90.65866470336914" zd="46.0"/>
    <point x="750" y="299" z="46" xd="226.64666175842285" yd="90.35646915435791" zd="46.0"/>
    <point x="749" y="298" z="46" xd="226.34446620941162" yd="90.05427360534668" zd="46.0"/>
    <point x="748" y="298" z="46" xd="226.0422706604004" yd="90.05427360534668" zd="46.0"/>
    <point x="747" y="297" z="46" xd="225.74007511138916" yd="89.75207805633545" zd="46.0"/>
    <point x="746" y="297" z="46" xd="225.43787956237793" yd="89.75207805633545" zd="46.0"/>
    <point x="745" y="296" z="46" xd="225.1356840133667" yd="89.44988250732422" zd="46.0"/>
    <point x="744" y="296" z="46" xd="224.83348846435547" yd="89.44988250732422" zd="46.0"/>
    <point x="743" y="295" z="46" xd="224.53129291534424" yd="89.14768695831299" zd="46.0"/>
    <point x="742" y="294" z="46" xd="224.229097366333" yd="88.84549140930176" zd="46.0"/>
    <point x="741" y="294" z="46" xd="223.92690181732178" yd="88.84549140930176" zd="46.0"/>
    <point x="740" y="293" z="46" xd="223.62470626831055" yd="88.54329586029053" zd="46.0"/>
    <point x="739" y="292" z="46" xd="223.32251071929932" yd="88.2411003112793" zd="46.0"/>
    <point x="738" y="291" z="46" xd="223.0203151702881" yd="87.93890476226807" zd="46.0"/>
    <point x="737" y="291" z="46" xd="222.71811962127686" yd="87.93890476226807" zd="46.0"/>
    <point x="736" y="290" z="46" xd="222.41592407226562" yd="87.63670921325684" zd="46.0"/>
    <point x="735" y="290" z="46" xd="222.1137285232544" yd="87.63670921325684" zd="46.0"/>
    <point x="734" y="289" z="46" xd="221.81153297424316" yd="87.3345136642456" zd="46.0"/>
    <point x="733" y="288" z="46" xd="221.50933742523193" yd="87.03231811523438" zd="46.0"/>
    <point x="732" y="288" z="46" xd="221.2071418762207" yd="87.03231811523438" zd="46.0"/>
    <point x="731" y="287" z="46" xd="220.90494632720947" yd="86.73012256622314" zd="46.0"/>
    <point x="730" y="287" z="46" xd="220.60275077819824" yd="86.73012256622314" zd="46.0"/>
    <point x="729" y="286" z="46" xd="220.300555229187" yd="86.42792701721191" zd="46.0"/>
    <point x="728" y="286" z="46" xd="219.99835968017578" yd="86.42792701721191" zd="46.0"/>