<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE tracings [
  <!ELEMENT tracings       (samplespacing,imagesize,path*,fill*)>
  <!ELEMENT imagesize      EMPTY>
  <!ELEMENT samplespacing  EMPTY>
  <!ELEMENT path           (point+)>
  <!ELEMENT point          EMPTY>
  <!ELEMENT fill           (node*)>
  <!ELEMENT node           EMPTY>
  <!ATTLIST samplespacing  x                 CDATA           #REQUIRED>
  <!ATTLIST samplespacing  y                 CDATA           #REQUIRED>
  <!ATTLIST samplespacing  z                 CDATA           #REQUIRED>
  <!ATTLIST samplespacing  units             CDATA           #REQUIRED>
  <!ATTLIST imagesize      width             CDATA           #REQUIRED>
  <!ATTLIST imagesize      height            CDATA           #REQUIRED>
  <!ATTLIST imagesize      depth             CDATA           #REQUIRED>
  <!ATTLIST path           id                CDATA           #REQUIRED>
  <!ATTLIST path           primary           CDATA           #IMPLIED>
  <!ATTLIST path           name              CDATA           #IMPLIED>
  <!ATTLIST path           startson          CDATA           #IMPLIED>
  <!ATTLIST path           startsindex       CDATA           #IMPLIED>
  <!ATTLIST path           startsx           CDATA           #IMPLIED>
  <!ATTLIST path           startsy           CDATA           #IMPLIED>
  <!ATTLIST path           startsz           CDATA           #IMPLIED>
  <!ATTLIST path           endson            CDATA           #IMPLIED>
  <!ATTLIST path           endsindex         CDATA           #IMPLIED>
  <!ATTLIST path           endsx             CDATA           #IMPLIED>
  <!ATTLIST path           endsy             CDATA           #IMPLIED>
  <!ATTLIST path           endsz             CDATA           #IMPLIED>
  <!ATTLIST path           reallength        CDATA           #IMPLIED>
  <!ATTLIST path           usefitted         (true|false)    #IMPLIED>
  <!ATTLIST path           fitted            CDATA           #IMPLIED>
  <!ATTLIST path           fittedversionof   CDATA           #IMPLIED>
  <!ATTLIST path           swctype           CDATA           #IMPLIED>
  <!ATTLIST path           color             CDATA           #IMPLIED>
  <!ATTLIST point          x                 CDATA           #REQUIRED>
  <!ATTLIST point          y                 CDATA           #REQUIRED>
  <!ATTLIST point          z                 CDATA           #REQUIRED>
  <!ATTLIST point          xd                CDATA           #IMPLIED>
  <!ATTLIST point          yd                CDATA           #IMPLIED>
  <!ATTLIST point          zd                CDATA           #IMPLIED>
  <!ATTLIST point          tx                CDATA           #IMPLIED>
  <!ATTLIST point          ty                CDATA           #IMPLIED>
  <!ATTLIST point          tz                CDATA           #IMPLIED>
  <!ATTLIST point          r                 CDATA           #IMPLIED>
  <!ATTLIST fill           id                CDATA           #REQUIRED>
  <!ATTLIST fill           frompaths         CDATA           #IMPLIED>
  <!ATTLIST fill           metric            CDATA           #REQUIRED>
  <!ATTLIST fill           threshold         CDATA           #REQUIRED>
  <!ATTLIST fill           volume            CDATA           #IMPLIED>
  <!ATTLIST node           id                CDATA           #REQUIRED>
  <!ATTLIST node           x                 CDATA           #REQUIRED>
  <!ATTLIST node           y                 CDATA           #REQUIRED>
  <!ATTLIST node           z                 CDATA           #REQUIRED>
  <!ATTLIST node           previousid        CDATA           #IMPLIED>
  <!ATTLIST node           distance          CDATA           #REQUIRED>
  <!ATTLIST node           status            (open|closed)   #REQUIRED>
]>

<tracings>
  <samplespacing x="0.2308487892150879" y="0.2308487892150879" z="1.0" units="microns"/>
  <imagesize width="1024" height="1024" depth="80"/>
  <path id="0" swctype="1" color="none" usefitted="true" fitted="12" name="Path (0)" reallength="30.18799288891831">
    <point x="348" y="454" z="28" xd="80.33537864685059" yd="104.8053503036499" zd="28.0"/>
    <point x="349" y="454" z="28" xd="80.56622743606567" yd="104.8053503036499" zd="28.0"/>
    <point x="350" y="454" z="28" xd="80.79707622528076" yd="104.8053503036499" zd="28.0"/>
    <point x="351" y="454" z="28" xd="81.02792501449585" yd="104.8053503036499" zd="28.0"/>
    <point x="352" y="454" z="28" xd="81.25877380371094" yd="104.8053503036499" zd="28.0"/>
    <point x="353" y="454" z="28" xd="81.48962259292603" yd="104.8053503036499" zd="28.0"/>
    <point x="354" y="454" z="28" xd="81.72047138214111" yd="104.8053503036499" zd="28.0"/>
    <point x="355" y="454" z="28" xd="81.9513201713562" yd="104.8053503036499" zd="28.0"/>
    <point x="356" y="454" z="28" xd="82.18216896057129" yd="104.8053503036499" zd="28.0"/>
    <point x="357" y="454" z="28" xd="82.41301774978638" yd="104.8053503036499" zd="28.0"/>
    <point x="358" y="454" z="28" xd="82.64386653900146" yd="104.8053503036499" zd="28.0"/>
    <point x="359" y="454" z="28" xd="82.87471532821655" yd="104.8053503036499" zd="28.0"/>
    <point x="360" y="454" z="28" xd="83.10556411743164" yd="104.8053503036499" zd="28.0"/>
    <point x="361" y="454" z="28" xd="83.33641290664673" yd="104.8053503036499" zd="28.0"/>
    <point x="362" y="454" z="28" xd="83.56726169586182" yd="104.8053503036499" zd="28.0"/>
    <point x="363" y="454" z="28" xd="83.7981104850769" yd="104.8053503036499" zd="28.0"/>
    <point x="364" y="454" z="28" xd="84.02895927429199" yd="104.8053503036499" zd="28.0"/>
    <point x="365" y="454" z="28" xd="84.25980806350708" yd="104.8053503036499" zd="28.0"/>
    <point x="366" y="454" z="28" xd="84.49065685272217" yd="104.8053503036499" zd="28.0"/>
    <point x="367" y="454" z="28" xd="84.72150564193726" yd="104.8053503036499" zd="28.0"/>
    <point x="368" y="454" z="28" xd="84.95235443115234" yd="104.8053503036499" zd="28.0"/>
    <point x="369" y="454" z="28" xd="85.18320322036743" yd="104.8053503036499" zd="28.0"/>
    <point x="370" y="454" z="28" xd="85.41405200958252" yd="104.8053503036499" zd="28.0"/>
    <point x="371" y="454" z="28" xd="85.64490079879761" yd="104.8053503036499" zd="28.0"/>
    <point x="372" y="454" z="28" xd="85.8757495880127" yd="104.8053503036499" zd="28.0"/>
    <point x="373" y="454" z="28" xd="86.10659837722778" yd="104.8053503036499" zd="28.0"/>
    <point x="374" y="454" z="28" xd="86.33744716644287" yd="104.8053503036499" zd="28.0"/>
    <point x="375" y="454" z="28" xd="86.56829595565796" yd="104.8053503036499" zd="28.0"/>
    <point x="376" y="454" z="28" xd="86.79914474487305" yd="104.8053503036499" zd="28.0"/>
    <point x="377" y="454" z="28" xd="87.02999353408813" yd="104.8053503036499" zd="28.0"/>
    <point x="378" y="454" z="28" xd="87.26084232330322" yd="104.8053503036499" zd="28.0"/>
    <point x="379" y="455" z="28" xd="87.49169111251831" yd="105.03619909286499" zd="28.0"/>
    <point x="380" y="456" z="28" xd="87.7225399017334" yd="105.26704788208008" zd="28.0"/>
    <point x="381" y="457" z="28" xd="87.95338869094849" yd="105.49789667129517" zd="28.0"/>
    <point x="382" y="457" z="28" xd="88.18423748016357" yd="105.49789667129517" zd="28.0"/>
    <point x="383" y="457" z="28" xd="88.41508626937866" yd="105.49789667129517" zd="28.0"/>
    <point x="384" y="457" z="28" xd="88.64593505859375" yd="105.49789667129517" zd="28.0"/>
    <point x="385" y="458" z="28" xd="88.87678384780884" yd="105.72874546051025" zd="28.0"/>
    <point x="386" y="458" z="28" xd="89.10763263702393" yd="105.72874546051025" zd="28.0"/>
    <point x="387" y="458" z="28" xd="89.33848142623901" yd="105.72874546051025" zd="28.0"/>
    <point x="388" y="458" z="28" xd="89.5693302154541" yd="105.72874546051025" zd="28.0"/>
    <point x="389" y="458" z="28" xd="89.80017900466919" yd="105.72874546051025" zd="28.0"/>
    <point x="390" y="458" z="28" xd="90.03102779388428" yd="105.72874546051025" zd="28.0"/>
    <point x="391" y="458" z="28" xd="90.26187658309937" yd="105.72874546051025" zd="28.0"/>
    <point x="392" y="458" z="28" xd="90.49272537231445" yd="105.72874546051025" zd="28.0"/>
    <point x="393" y="458" z="28" xd="90.72357416152954" yd="105.72874546051025" zd="28.0"/>
    <point x="394" y="458" z="28" xd="90.95442295074463" yd="105.72874546051025" zd="28.0"/>
    <point x="395" y="458" z="28" xd="91.18527173995972" yd="105.72874546051025" zd="28.0"/>
    <point x="396" y="458" z="28" xd="91.4161205291748" yd="105.72874546051025" zd="28.0"/>
    <point x="397" y="458" z="28" xd="91.64696931838989" yd="105.72874546051025" zd="28.0"/>
    <point x="398" y="458" z="28" xd="91.87781810760498" yd="105.72874546051025" zd="28.0"/>
    <point x="399" y="458" z="28" xd="92.10866689682007" yd="105.72874546051025" zd="28.0"/>
    <point x="400" y="458" z="28" xd="92.33951568603516" yd="105.72874546051025" zd="28.0"/>
    <point x="401" y="458" z="28" xd="92.57036447525024" yd="105.72874546051025" zd="28.0"/>
    <point x="402" y="458" z="28" xd="92.80121326446533" yd="105.72874546051025" zd="28.0"/>
    <point x="403" y="458" z="28" xd="93.03206205368042" yd="105.72874546051025" zd="28.0"/>
    <point x="404" y="458" z="28" xd="93.26291084289551" yd="105.72874546051025" zd="28.0"/>
    <point x="405" y="458" z="28" xd="93.4937596321106" yd="105.72874546051025" zd="28.0"/>
    <point x="406" y="458" z="28" xd="93.72460842132568" yd="105.72874546051025" zd="28.0"/>
    <point x="407" y="458" z="28" xd="93.95545721054077" yd="105.72874546051025" zd="28.0"/>
    <point x="408" y="458" z="28" xd="94.18630599975586" yd="105.72874546051025" zd="28.0"/>
    <point x="409" y="458" z="28" xd="94.41715478897095" yd="105.72874546051025" zd="28.0"/>
    <point x="410" y="458" z="28" xd="94.64800357818604" yd="105.72874546051025" zd="28.0"/>
    <point x="411" y="458" z="28" xd="94.87885236740112" yd="105.72874546051025" zd="28.0"/>
    <point x="412" y="458" z="28" xd="95.10970115661621" yd="105.72874546051025" zd="28.0"/>
    <point x="413" y="458" z="28" xd="95.3405499458313" yd="105.72874546051025" zd="28.0"/>
    <point x="414" y="457" z="28" xd="95.57139873504639" yd="105.49789667129517" zd="28.0"/>
    <point x="415" y="457" z="28" xd="95.80224752426147" yd="105.49789667129517" zd="28.0"/>
    <point x="416" y="457" z="28" xd="96.03309631347656" yd="105.49789667129517" zd="28.0"/>
    <point x="417" y="457" z="28" xd="96.26394510269165" yd="105.49789667129517" zd="28.0"/>
    <point x="418" y="457" z="28" xd="96.49479389190674" yd="105.49789667129517" zd="28.0"/>
    <point x="419" y="457" z="28" xd="96.72564268112183" yd="105.49789667129517" zd="28.0"/>
    <point x="420" y="457" z="28" xd="96.95649147033691" yd="105.49789667129517" zd="28.0"/>
    <point x="421" y="457" z="28" xd="97.187340259552" yd="105.49789667129517" zd="28.0"/>
    <point x="422" y="457" z="28" xd="97.41818904876709" yd="105.49789667129517" zd="28.0"/>
    <point x="423" y="457" z="28" xd="97.64903783798218" yd="105.49789667129517" zd="28.0"/>
    <point x="424" y="457" z="28" xd="97.87988662719727" yd="105.49789667129517" zd="28.0"/>
    <point x="425" y="457" z="28" xd="98.11073541641235" yd="105.49789667129517" zd="28.0"/>
    <point x="426" y="457" z="28" xd="98.34158420562744" yd="105.49789667129517" zd="28.0"/>
    <point x="427" y="457" z="28" xd="98.57243299484253" yd="105.49789667129517" zd="28.0"/>
    <point x="428" y="457" z="28" xd="98.80328178405762" yd="105.49789667129517" zd="28.0"/>
    <point x="429" y="457" z="28" xd="99.0341305732727" yd="105.49789667129517" zd="28.0"/>
    <point x="430" y="456" z="28" xd="99.2649793624878" yd="105.26704788208008" zd="28.0"/>
    <point x="431" y="456" z="28" xd="99.49582815170288" yd="105.26704788208008" zd="28.0"/>
    <point x="432" y="456" z="28" xd="99.72667694091797" yd="105.26704788208008" zd="28.0"/>
    <point x="433" y="455" z="28" xd="99.95752573013306" yd="105.03619909286499" zd="28.0"/>
    <point x="434" y="455" z="28" xd="100.18837451934814" yd="105.03619909286499" zd="28.0"/>
    <point x="435" y="455" z="28" xd="100.41922330856323" yd="105.03619909286499" zd="28.0"/>
    <point x="436" y="454" z="28" xd="100.65007209777832" yd="104.8053503036499" zd="28.0"/>
    <point x="437" y="454" z="28" xd="100.88092088699341" yd="104.8053503036499" zd="28.0"/>
    <point x="438" y="454" z="28" xd="101.1117696762085" yd="104.8053503036499" zd="28.0"/>
    <point x="439" y="453" z="28" xd="101.34261846542358" yd="104.57450151443481" zd="28.0"/>
    <point x="440" y="453" z="28" xd="101.57346725463867" yd="104.57450151443481" zd="28.0"/>
    <point x="441" y="453" z="28" xd="101.80431604385376" yd="104.57450151443481" zd="28.0"/>
    <point x="442" y="452" z="28" xd="102.03516483306885" yd="104.34365272521973" zd="28.0"/>
    <point x="443" y="451" z="28" xd="102.26601362228394" yd="104.11280393600464" zd="28.0"/>
    <point x="444" y="450" z="28" xd="102.49686241149902" yd="103.88195514678955" zd="28.0"/>
    <point x="445" y="449" z="28" xd="102.72771120071411" yd="103.65110635757446" zd="28.0"/>
    <point x="446" y="448" z="28" xd="102.9585599899292" yd="103.42025756835938" zd="28.0"/>
    <point x="447" y="447" z="28" xd="103.18940877914429" yd="103.18940877914429" zd="28.0"/>
    <point x="448" y="447" z="28" xd="103.42025756835938" yd="103.18940877914429" zd="28.0"/>
    <point x="449" y="446" z="28" xd="103.65110635757446" yd="102.9585599899292" zd="28.0"/>
    <point x="450" y="445" z="28" xd="103.88195514678955" yd="102.72771120071411" zd="28.0"/>
    <point x="451" y="444" z="28" xd="104.11280393600464" yd="102.49686241149902" zd="28.0"/>
    <point x="452" y="443" z="28" xd="104.34365272521973" yd="102.26601362228394" zd="28.0"/>
    <point x="453" y="442" z="28" xd="104.57450151443481" yd="102.03516483306885" zd="28.0"/>
    <point x="454" y="441" z="28" xd="104.8053503036499" yd="101.80431604385376" zd="28.0"/>
    <point x="455" y="441" z="28" xd="105.03619909286499" yd="101.80431604385376" zd="28.0"/>
    <point x="456" y="441" z="28" xd="105.26704788208008" yd="101.80431604385376" zd="28.0"/>
    <point x="457" y="440" z="28" xd="105.49789667129517" yd="101.57346725463867" zd="28.0"/>
    <point x="458" y="440" z="28" xd="105.72874546051025" yd="101.57346725463867" zd="28.0"/>
    <point x="459" y="439" z="28" xd="105.95959424972534" yd="101.34261846542358" zd="28.0"/>
    <point x="460" y="438" z="28" xd="106.19044303894043" yd="101.1117696762085" zd="28.0"/>
    <point x="461" y="438" z="28" xd="106.42129182815552" yd="101.1117696762085" zd="28.0"/>
    <point x="462" y="437" z="28" xd="106.6521406173706" yd="100.88092088699341" zd="28.0"/>
    <point x="463" y="436" z="28" xd="106.8829894065857" yd="100.65007209777832" zd="28.0"/>
    <point x="464" y="436" z="28" xd="107.11383819580078" yd="100.65007209777832" zd="28.0"/>
    <point x="465" y="436" z="28" xd="107.34468698501587" yd="100.65007209777832" zd="28.0"/>
    <point x="466" y="436" z="28" xd="107.57553577423096" yd="100.65007209777832" zd="28.0"/>
    <point x="467" y="436" z="28" xd="107.80638456344604" yd="100.65007209777832" zd="28.0"/>
    <point x="468" y="436" z="28" xd="108.03723335266113" yd="100.65007209777832" zd="28.0"/>
  </path>
  <path id="4" swctype="3" color="none" usefitted="true" fitted="13" startson="0" startx="108.03723335266113" starty="100.65007209777832" startz="28.0" startsindex="120" name="Path (4)" reallength="31.893591320809627">
    <point x="468" y="436" z="28" xd="108.03723335266113" yd="100.65007209777832" zd="28.0"/>
    <point x="469" y="437" z="27" xd="108.26808214187622" yd="100.88092088699341" zd="27.0"/>
    <point x="470" y="437" z="27" xd="108.49893093109131" yd="100.88092088699341" zd="27.0"/>
    <point x="471" y="437" z="27" xd="108.7297797203064" yd="100.88092088699341" zd="27.0"/>
    <point x="472" y="437" z="27" xd="108.96062850952148" yd="100.88092088699341" zd="27.0"/>
    <point x="473" y="437" z="27" xd="109.19147729873657" yd="100.88092088699341" zd="27.0"/>
    <point x="474" y="437" z="27" xd="109.42232608795166" yd="100.88092088699341" zd="27.0"/>
    <point x="475" y="438" z="27" xd="109.65317487716675" yd="101.1117696762085" zd="27.0"/>
    <point x="476" y="438" z="27" xd="109.88402366638184" yd="101.1117696762085" zd="27.0"/>
    <point x="477" y="438" z="27" xd="110.11487245559692" yd="101.1117696762085" zd="27.0"/>
    <point x="478" y="438" z="27" xd="110.34572124481201" yd="101.1117696762085" zd="27.0"/>
    <point x="479" y="438" z="27" xd="110.5765700340271" yd="101.1117696762085" zd="27.0"/>
    <point x="480" y="438" z="27" xd="110.80741882324219" yd="101.1117696762085" zd="27.0"/>
    <point x="481" y="438" z="27" xd="111.03826761245728" yd="101.1117696762085" zd="27.0"/>
    <point x="482" y="438" z="27" xd="111.26911640167236" yd="101.1117696762085" zd="27.0"/>
    <point x="483" y="439" z="26" xd="111.49996519088745" yd="101.34261846542358" zd="26.0"/>
    <point x="484" y="439" z="26" xd="111.73081398010254" yd="101.34261846542358" zd="26.0"/>
    <point x="485" y="439" z="26" xd="111.96166276931763" yd="101.34261846542358" zd="26.0"/>
    <point x="486" y="439" z="26" xd="112.19251155853271" yd="101.34261846542358" zd="26.0"/>
    <point x="487" y="440" z="26" xd="112.4233603477478" yd="101.57346725463867" zd="26.0"/>
    <point x="488" y="440" z="26" xd="112.65420913696289" yd="101.57346725463867" zd="26.0"/>
    <point x="489" y="440" z="26" xd="112.88505792617798" yd="101.57346725463867" zd="26.0"/>
    <point x="490" y="440" z="26" xd="113.11590671539307" yd="101.57346725463867" zd="26.0"/>
    <point x="491" y="440" z="26" xd="113.34675550460815" yd="101.57346725463867" zd="26.0"/>
    <point x="492" y="441" z="26" xd="113.57760429382324" yd="101.80431604385376" zd="26.0"/>
    <point x="493" y="441" z="26" xd="113.80845308303833" yd="101.80431604385376" zd="26.0"/>
    <point x="494" y="441" z="26" xd="114.03930187225342" yd="101.80431604385376" zd="26.0"/>
    <point x="495" y="442" z="26" xd="114.2701506614685" yd="102.03516483306885" zd="26.0"/>
    <point x="496" y="442" z="26" xd="114.5009994506836" yd="102.03516483306885" zd="26.0"/>
    <point x="497" y="442" z="26" xd="114.73184823989868" yd="102.03516483306885" zd="26.0"/>
    <point x="498" y="442" z="26" xd="114.96269702911377" yd="102.03516483306885" zd="26.0"/>
    <point x="499" y="442" z="26" xd="115.19354581832886" yd="102.03516483306885" zd="26.0"/>
    <point x="500" y="443" z="26" xd="115.42439460754395" yd="102.26601362228394" zd="26.0"/>
    <point x="501" y="443" z="26" xd="115.65524339675903" yd="102.26601362228394" zd="26.0"/>
    <point x="502" y="443" z="26" xd="115.88609218597412" yd="102.26601362228394" zd="26.0"/>
    <point x="503" y="443" z="26" xd="116.11694097518921" yd="102.26601362228394" zd="26.0"/>
    <point x="504" y="444" z="26" xd="116.3477897644043" yd="102.49686241149902" zd="26.0"/>
    <point x="505" y="444" z="26" xd="116.57863855361938" yd="102.49686241149902" zd="26.0"/>
    <point x="506" y="444" z="26" xd="116.80948734283447" yd="102.49686241149902" zd="26.0"/>
    <point x="507" y="445" z="26" xd="117.04033613204956" yd="102.72771120071411" zd="26.0"/>
    <point x="508" y="445" z="26" xd="117.27118492126465" yd="102.72771120071411" zd="26.0"/>
    <point x="509" y="445" z="26" xd="117.50203371047974" yd="102.72771120071411" zd="26.0"/>
    <point x="510" y="445" z="26" xd="117.73288249969482" yd="102.72771120071411" zd="26.0"/>
    <point x="511" y="445" z="26" xd="117.96373128890991" yd="102.72771120071411" zd="26.0"/>
    <point x="512" y="445" z="26" xd="118.194580078125" yd="102.72771120071411" zd="26.0"/>
    <point x="513" y="446" z="26" xd="118.42542886734009" yd="102.9585599899292" zd="26.0"/>
    <point x="514" y="446" z="26" xd="118.65627765655518" yd="102.9585599899292" zd="26.0"/>
    <point x="515" y="446" z="26" xd="118.88712644577026" yd="102.9585599899292" zd="26.0"/>
    <point x="516" y="446" z="26" xd="119.11797523498535" yd="102.9585599899292" zd="26.0"/>
    <point x="517" y="447" z="26" xd="119.34882402420044" yd="103.18940877914429" zd="26.0"/>
    <point x="518" y="447" z="26" xd="119.57967281341553" yd="103.18940877914429" zd="26.0"/>
    <point x="519" y="447" z="26" xd="119.81052160263062" yd="103.18940877914429" zd="26.0"/>
    <point x="520" y="447" z="26" xd="120.0413703918457" yd="103.18940877914429" zd="26.0"/>
    <point x="521" y="447" z="26" xd="120.27221918106079" yd="103.18940877914429" zd="26.0"/>
    <point x="522" y="448" z="27" xd="120.50306797027588" yd="103.42025756835938" zd="27.0"/>
    <point x="523" y="449" z="27" xd="120.73391675949097" yd="103.65110635757446" zd="27.0"/>
    <point x="524" y="450" z="27" xd="120.96476554870605" yd="103.88195514678955" zd="27.0"/>
    <point x="525" y="450" z="27" xd="121.19561433792114" yd="103.88195514678955" zd="27.0"/>
    <point x="526" y="450" z="27" xd="121.42646312713623" yd="103.88195514678955" zd="27.0"/>
    <point x="527" y="450" z="27" xd="121.65731191635132" yd="103.88195514678955" zd="27.0"/>
    <point x="528" y="450" z="27" xd="121.8881607055664" yd="103.88195514678955" zd="27.0"/>
    <point x="529" y="450" z="27" xd="122.1190094947815" yd="103.88195514678955" zd="27.0"/>
    <point x="530" y="450" z="27" xd="122.34985828399658" yd="103.88195514678955" zd="27.0"/>
    <point x="531" y="450" z="27" xd="122.58070707321167" yd="103.88195514678955" zd="27.0"/>
    <point x="532" y="450" z="27" xd="122.81155586242676" yd="103.88195514678955" zd="27.0"/>
    <point x="533" y="450" z="27" xd="123.04240465164185" yd="103.88195514678955" zd="27.0"/>
    <point x="534" y="450" z="27" xd="123.27325344085693" yd="103.88195514678955" zd="27.0"/>
    <point x="535" y="450" z="27" xd="123.50410223007202" yd="103.88195514678955" zd="27.0"/>
    <point x="536" y="450" z="27" xd="123.73495101928711" yd="103.88195514678955" zd="27.0"/>
    <point x="537" y="450" z="27" xd="123.9657998085022" yd="103.88195514678955" zd="27.0"/>
    <point x="538" y="450" z="27" xd="124.19664859771729" yd="103.88195514678955" zd="27.0"/>
    <point x="539" y="450" z="27" xd="124.42749738693237" yd="103.88195514678955" zd="27.0"/>
    <point x="540" y="450" z="27" xd="124.65834617614746" yd="103.88195514678955" zd="27.0"/>
    <point x="541" y="450" z="27" xd="124.88919496536255" yd="103.88195514678955" zd="27.0"/>
    <point x="542" y="450" z="27" xd="125.12004375457764" yd="103.88195514678955" zd="27.0"/>
    <point x="543" y="450" z="27" xd="125.35089254379272" yd="103.88195514678955" zd="27.0"/>
    <point x="544" y="449" z="27" xd="125.58174133300781" yd="103.65110635757446" zd="27.0"/>
    <point x="545" y="448" z="27" xd="125.8125901222229" yd="103.42025756835938" zd="27.0"/>
    <point x="546" y="448" z="27" xd="126.04343891143799" yd="103.42025756835938" zd="27.0"/>
    <point x="547" y="448" z="27" xd="126.27428770065308" yd="103.42025756835938" zd="27.0"/>
    <point x="548" y="447" z="27" xd="126.50513648986816" yd="103.18940877914429" zd="27.0"/>
    <point x="549" y="447" z="27" xd="126.73598527908325" yd="103.18940877914429" zd="27.0"/>
    <point x="550" y="447" z="27" xd="126.96683406829834" yd="103.18940877914429" zd="27.0"/>
    <point x="551" y="447" z="27" xd="127.19768285751343" yd="103.18940877914429" zd="27.0"/>
    <point x="552" y="447" z="27" xd="127.42853164672852" yd="103.18940877914429" zd="27.0"/>
    <point x="553" y="447" z="27" xd="127.6593804359436" yd="103.18940877914429" zd="27.0"/>
    <point x="554" y="447" z="27" xd="127.89022922515869" yd="103.18940877914429" zd="27.0"/>
    <point x="555" y="446" z="27" xd="128.12107801437378" yd="102.9585599899292" zd="27.0"/>
    <point x="556" y="446" z="27" xd="128.35192680358887" yd="102.9585599899292" zd="27.0"/>
    <point x="557" y="446" z="27" xd="128.58277559280396" yd="102.9585599899292" zd="27.0"/>
    <point x="558" y="446" z="27" xd="128.81362438201904" yd="102.9585599899292" zd="27.0"/>
    <point x="559" y="446" z="27" xd="129.04447317123413" yd="102.9585599899292" zd="27.0"/>
    <point x="560" y="446" z="27" xd="129.27532196044922" yd="102.9585599899292" zd="27.0"/>
    <point x="561" y="446" z="27" xd="129.5061707496643" yd="102.9585599899292" zd="27.0"/>
    <point x="562" y="446" z="27" xd="129.7370195388794" yd="102.9585599899292" zd="27.0"/>
    <point x="563" y="446" z="27" xd="129.96786832809448" yd="102.9585599899292" zd="27.0"/>
    <point x="564" y="446" z="27" xd="130.19871711730957" yd="102.9585599899292" zd="27.0"/>
    <point x="565" y="446" z="28" xd="130.42956590652466" yd="102.9585599899292" zd="28.0"/>
    <point x="566" y="446" z="28" xd="130.66041469573975" yd="102.9585599899292" zd="28.0"/>
    <point x="567" y="446" z="28" xd="130.89126348495483" yd="102.9585599899292" zd="28.0"/>
    <point x="568" y="446" z="28" xd="131.12211227416992" yd="102.9585599899292" zd="28.0"/>
    <point x="569" y="446" z="28" xd="131.352961063385" yd="102.9585599899292" zd="28.0"/>
    <point x="570" y="445" z="28" xd="131.5838098526001" yd="102.72771120071411" zd="28.0"/>
    <point x="571" y="445" z="28" xd="131.81465864181519" yd="102.72771120071411" zd="28.0"/>
    <point x="572" y="444" z="28" xd="132.04550743103027" yd="102.49686241149902" zd="28.0"/>
    <point x="573" y="444" z="28" xd="132.27635622024536" yd="102.49686241149902" zd="28.0"/>
    <point x="574" y="444" z="28" xd="132.50720500946045" yd="102.49686241149902" zd="28.0"/>
    <point x="575" y="444" z="28" xd="132.73805379867554" yd="102.49686241149902" zd="28.0"/>
    <point x="576" y="444" z="28" xd="132.96890258789062" yd="102.49686241149902" zd="28.0"/>
    <point x="577" y="444" z="28" xd="133.1997513771057" yd="102.49686241149902" zd="28.0"/>
    <point x="578" y="444" z="28" xd="133.4306001663208" yd="102.49686241149902" zd="28.0"/>
    <point x="579" y="444" z="28" xd="133.6614489555359" yd="102.49686241149902" zd="28.0"/>
    <point x="580" y="444" z="28" xd="133.89229774475098" yd="102.49686241149902" zd="28.0"/>
    <point x="581" y="444" z="28" xd="134.12314653396606" yd="102.49686241149902" zd="28.0"/>
    <point x="582" y="444" z="28" xd="134.35399532318115" yd="102.49686241149902" zd="28.0"/>
    <point x="583" y="444" z="28" xd="134.58484411239624" yd="102.49686241149902" zd="28.0"/>
    <point x="584" y="444" z="28" xd="134.81569290161133" yd="102.49686241149902" zd="28.0"/>
    <point x="585" y="444" z="28" xd="135.04654169082642" yd="102.49686241149902" zd="28.0"/>
  </path>
  <path id="5" swctype="3" color="none" usefitted="true" fitted="14" startson="4" startx="135.04654169082642" starty="102.49686241149902" startz="28.0" startsindex="117" name="Path (5)" reallength="14.832029771150747">
    <point x="585" y="444" z="28" xd="135.04654169082642" yd="102.49686241149902" zd="28.0"/>
    <point x="584" y="443" z="28" xd="134.81569290161133" yd="102.26601362228394" zd="28.0"/>
    <point x="583" y="442" z="29" xd="134.58484411239624" yd="102.03516483306885" zd="29.0"/>
    <point x="583" y="441" z="30" xd="134.58484411239624" yd="101.80431604385376" zd="30.0"/>
    <point x="583" y="440" z="30" xd="134.58484411239624" yd="101.57346725463867" zd="30.0"/>
    <point x="583" y="439" z="30" xd="134.58484411239624" yd="101.34261846542358" zd="30.0"/>
    <point x="583" y="438" z="30" xd="134.58484411239624" yd="101.1117696762085" zd="30.0"/>
    <point x="583" y="437" z="30" xd="134.58484411239624" yd="100.88092088699341" zd="30.0"/>
    <point x="584" y="436" z="30" xd="134.81569290161133" yd="100.65007209777832" zd="30.0"/>
    <point x="584" y="435" z="30" xd="134.81569290161133" yd="100.41922330856323" zd="30.0"/>
    <point x="584" y="434" z="30" xd="134.81569290161133" yd="100.18837451934814" zd="30.0"/>
    <point x="584" y="433" z="30" xd="134.81569290161133" yd="99.95752573013306" zd="30.0"/>
    <point x="584" y="432" z="30" xd="134.81569290161133" yd="99.72667694091797" zd="30.0"/>
    <point x="584" y="431" z="30" xd="134.81569290161133" yd="99.49582815170288" zd="30.0"/>
    <point x="584" y="430" z="30" xd="134.81569290161133" yd="99.2649793624878" zd="30.0"/>
    <point x="584" y="429" z="30" xd="134.81569290161133" yd="99.0341305732727" zd="30.0"/>
    <point x="585" y="428" z="31" xd="135.04654169082642" yd="98.80328178405762" zd="31.0"/>
    <point x="585" y="427" z="31" xd="135.04654169082642" yd="98.57243299484253" zd="31.0"/>
    <point x="585" y="426" z="31" xd="135.04654169082642" yd="98.34158420562744" zd="31.0"/>
    <point x="585" y="425" z="31" xd="135.04654169082642" yd="98.11073541641235" zd="31.0"/>
    <point x="585" y="424" z="31" xd="135.04654169082642" yd="97.87988662719727" zd="31.0"/>
    <point x="584" y="423" z="31" xd="134.81569290161133" yd="97.64903783798218" zd="31.0"/>
    <point x="584" y="422" z="31" xd="134.81569290161133" yd="97.41818904876709" zd="31.0"/>
    <point x="584" y="421" z="31" xd="134.81569290161133" yd="97.187340259552" zd="31.0"/>
    <point x="583" y="420" z="31" xd="134.58484411239624" yd="96.95649147033691" zd="31.0"/>
    <point x="583" y="419" z="31" xd="134.58484411239624" yd="96.72564268112183" zd="31.0"/>
    <point x="583" y="418" z="31" xd="134.58484411239624" yd="96.49479389190674" zd="31.0"/>
    <point x="582" y="417" z="31" xd="134.35399532318115" yd="96.26394510269165" zd="31.0"/>
    <point x="581" y="416" z="31" xd="134.12314653396606" yd="96.03309631347656" zd="31.0"/>
    <point x="580" y="415" z="31" xd="133.89229774475098" yd="95.80224752426147" zd="31.0"/>
    <point x="580" y="414" z="31" xd="133.89229774475098" yd="95.57139873504639" zd="31.0"/>
    <point x="579" y="413" z="31" xd="133.6614489555359" yd="95.3405499458313" zd="31.0"/>
    <point x="578" y="412" z="31" xd="133.4306001663208" yd="95.10970115661621" zd="31.0"/>
    <point x="578" y="411" z="31" xd="133.4306001663208" yd="94.87885236740112" zd="31.0"/>